import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/common/Footer";
import { StoreProvider } from "@/redux/StoreProvider";
import { SessionProvider } from "next-auth/react";
// import SyncCartOnLogin from "@/components/common/SyncCartOnLogin";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between `}
      >
          <StoreProvider>
            <SessionProvider>
              {/* <SyncCartOnLogin/> */}
              <Navbar/>
              {children}
            </SessionProvider>
          </StoreProvider>
        <Footer/>
      </body>
    </html>
  );
}
