import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/common/Footer";
import { StoreProvider } from "@/redux/StoreProvider";
import { SessionProvider } from "next-auth/react";
import CartCookie from "@/components/common/CartCookie";
// import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Meta Pixel Base Code */}
      {/* <Script id="meta-pixel" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '719451817264857');
            fbq('track', 'PageView');
          `}
        </Script> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between `}
      >
          <StoreProvider>
            <SessionProvider>
              <CartCookie/>
              <Navbar/>
              {children}
            </SessionProvider>
          </StoreProvider>
        <Footer/>
      </body>
    </html>
  );
}
